---
# Source: victoria-metrics-cluster/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: victoriametrics1-victoria-metrics-cluster-clusterrole
  labels:
    helm.sh/chart: victoria-metrics-cluster-0.11.12
    app.kubernetes.io/managed-by: Helm
rules: []
