---
# Source: victoria-metrics-cluster/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: victoriametrics1-victoria-metrics-cluster
  namespace: default
  labels:
    helm.sh/chart: victoria-metrics-cluster-0.11.12
    app.kubernetes.io/managed-by: Helm
rules: []
