---
# Source: victoria-metrics-cluster/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: victoriametrics1-victoria-metrics-cluster
  namespace: default
  labels:
    helm.sh/chart: victoria-metrics-cluster-0.11.12
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: victoriametrics1-victoria-metrics-cluster
subjects:
- kind: ServiceAccount
  name: victoriametrics1-victoria-metrics-cluster
  namespace: default
