---
# Source: victoria-metrics-cluster/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: victoria-metrics-cluster-0.11.12
    app.kubernetes.io/managed-by: Helm
  name: victoriametrics1-victoria-metrics-cluster
  namespace: default
