---
# Source: victoria-metrics-cluster/templates/vminsert-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vminsert
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/instance: victoriametrics1
    helm.sh/chart: victoria-metrics-cluster-0.11.12
    app.kubernetes.io/managed-by: Helm
  name: victoriametrics1-victoria-metrics-cluster-vminsert
  namespace: default
spec:
  selector:
    matchLabels:
      app: vminsert
      app.kubernetes.io/name: victoria-metrics-cluster
      app.kubernetes.io/instance: victoriametrics1
  replicas: 2
  template:
    metadata:
      labels:
        app: vminsert
        app.kubernetes.io/name: victoria-metrics-cluster
        app.kubernetes.io/instance: victoriametrics1
        app.kubernetes.io/managed-by: Helm
    spec:
      automountServiceAccountToken: true
      containers:
        - name: victoria-metrics-cluster-vminsert
          image: "victoriametrics/vminsert:v1.97.1-cluster"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            {}
          args:
            - --storageNode=victoriametrics1-victoria-metrics-cluster-vmstorage-0.victoriametrics1-victoria-metrics-cluster-vmstorage.default.svc.cluster.local:8400
            - --storageNode=victoriametrics1-victoria-metrics-cluster-vmstorage-1.victoriametrics1-victoria-metrics-cluster-vmstorage.default.svc.cluster.local:8400
            
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
          ports:
            - name: http
              containerPort: 8480
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            
          resources:
            {}
      serviceAccountName: victoriametrics1-victoria-metrics-cluster
