---
# Source: victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vmstorage
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/instance: victoriametrics1
    helm.sh/chart: victoria-metrics-cluster-0.11.12
    app.kubernetes.io/managed-by: Helm
  name: victoriametrics1-victoria-metrics-cluster-vmstorage
  namespace: default
spec:
  serviceName: victoriametrics1-victoria-metrics-cluster-vmstorage
  selector:
    matchLabels:
      app: vmstorage
      app.kubernetes.io/name: victoria-metrics-cluster
      app.kubernetes.io/instance: victoriametrics1
  replicas: 2
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: vmstorage
        app.kubernetes.io/name: victoria-metrics-cluster
        app.kubernetes.io/instance: victoriametrics1
        app.kubernetes.io/managed-by: Helm
    spec:
      automountServiceAccountToken: true
      containers:
        - name: victoria-metrics-cluster-vmstorage
          image: "victoriametrics/vmstorage:v1.97.1-cluster"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            {}
          args:
            - "--retentionPeriod=1"
            - "--storageDataPath=/storage"
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
          ports:
            - name: http
              containerPort: 8482
            - name: vminsert
              containerPort: 8400
            - name: vmselect
              containerPort: 8401
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          resources: 
            {}
          volumeMounts:
            - name: vmstorage-volume
              mountPath: /storage
              subPath: 
            
      serviceAccountName: victoriametrics1-victoria-metrics-cluster
      terminationGracePeriodSeconds: 60
      volumes:
        
  volumeClaimTemplates:
    - metadata:
        name: vmstorage-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "8Gi"
        storageClassName: "mylocalsc1"
